# Generated by Django 4.1.2 on 2022-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0003_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='identifier',
            field=models.IntegerField(unique=True),
        ),
    ]
