# Generated by Django 4.1.3 on 2022-11-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0006_pantry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantry',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
